#!/usr/bin/env bash
# Idempotent Cloud Agent install for Cursor Pulse (local dev mode).
# Prepares: Python .venv (dev+web extras), admin UI deps + build, local
# config.yaml/.env with dev secrets, SQLite schema/seed, and a portal owner.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# 1. System dependency: the default image's python3 lacks the venv/ensurepip
#    module, which the repo tooling (.venv/bin/pulse) requires.
if ! python3 -c 'import ensurepip' >/dev/null 2>&1; then
  echo "[install] installing python3-venv"
  sudo apt-get update -qq
  sudo apt-get install -y python3-venv
fi

# 2. Python virtualenv + project (dev tools + web server).
if [ ! -x .venv/bin/python ]; then
  echo "[install] creating .venv"
  python3 -m venv .venv
fi
.venv/bin/pip install -U pip
.venv/bin/pip install -e ".[dev,web]"

# 3. Admin UI: install deps and build into pulse/web/static so the API can
#    serve /admin/ standalone (Vite still runs separately for HMR).
if [ -f web-admin/package.json ]; then
  (cd web-admin && npm install && npm run build)
fi

# 4. Local config + dev secrets (git-ignored). ADMIN_PASSWORD honors an
#    injected secret; otherwise a known dev default so the UI is testable.
[ -f config.yaml ] || cp config.example.yaml config.yaml

if [ -f .env ]; then
  ADMIN_PW="$(.venv/bin/python - <<'PY'
from dotenv import dotenv_values
print(dotenv_values('.env').get('ADMIN_PASSWORD') or 'pulse-dev-admin')
PY
)"
else
  ADMIN_PW="${ADMIN_PASSWORD:-pulse-dev-admin}"
  JWT="$(.venv/bin/python -c 'import secrets;print(secrets.token_urlsafe(48))')"
  ENC="$(.venv/bin/python -c 'import secrets;print(secrets.token_urlsafe(48))')"
  cat > .env <<EOF
# Cursor Pulse local dev env (generated by Cloud Agent install; git-ignored).
BOT_PLATFORM=none
ADMIN_PASSWORD=${ADMIN_PW}
JWT_SECRET=${JWT}
PULSE_CREDENTIAL_ENCRYPTION_KEY=${ENC}
WEB_CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080
DINGTALK_OAUTH_REDIRECT_URI=http://localhost:5173/login/callback
EOF
fi

# 5. Database schema + catalog seed + portal owner (all idempotent).
.venv/bin/pulse -c config.yaml init-db
.venv/bin/pulse -c config.yaml admin bootstrap \
  --user-id admin --name "Admin" --password "$ADMIN_PW" --channel web

echo "[install] done. Admin login: admin / ${ADMIN_PW}"
